### ISSUE TITLE
Zdraste

### ISSUE THREAD

**Issue by 17etro** [JohnyKovalenko1337/react_front#1]
Я вот не поняв чого вже не по 20 комітов за день а 2-3?

**Comment by JohnyKovalenko1337** [comment]
Комміти стали більш обдуманими і правильними. 
![enaj](https://user-images.githubusercontent.com/51968301/86621725-5e513980-bfc7-11ea-88d8-5d27d4dd737e.png)

**Comment by 17etro** [comment]
niky9 smailik na piv liцa
